// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDglPQpq5ZlFOsWJlYD2xOE9c1VSmvBSms',
    appId: '1:590642798717:web:a64a1e49adf21a8f779114',
    messagingSenderId: '590642798717',
    projectId: 'kissan-connect-dcd06',
    authDomain: 'kissan-connect-dcd06.firebaseapp.com',
    storageBucket: 'kissan-connect-dcd06.firebasestorage.app',
    measurementId: 'G-JECBP9WDYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFptIYpzaaq241G8fjQ9F74aBWRa0Y4nM',
    appId: '1:590642798717:android:cc37010d66efdd6b779114',
    messagingSenderId: '590642798717',
    projectId: 'kissan-connect-dcd06',
    storageBucket: 'kissan-connect-dcd06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTwfkGisB-I1zvXP7kAAUBlTB0nLgQHtw',
    appId: '1:590642798717:ios:febdcab2a0183955779114',
    messagingSenderId: '590642798717',
    projectId: 'kissan-connect-dcd06',
    storageBucket: 'kissan-connect-dcd06.firebasestorage.app',
    iosBundleId: 'com.example.kissanConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTwfkGisB-I1zvXP7kAAUBlTB0nLgQHtw',
    appId: '1:590642798717:ios:febdcab2a0183955779114',
    messagingSenderId: '590642798717',
    projectId: 'kissan-connect-dcd06',
    storageBucket: 'kissan-connect-dcd06.firebasestorage.app',
    iosBundleId: 'com.example.kissanConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDglPQpq5ZlFOsWJlYD2xOE9c1VSmvBSms',
    appId: '1:590642798717:web:b1cdbef69e135158779114',
    messagingSenderId: '590642798717',
    projectId: 'kissan-connect-dcd06',
    authDomain: 'kissan-connect-dcd06.firebaseapp.com',
    storageBucket: 'kissan-connect-dcd06.firebasestorage.app',
    measurementId: 'G-7PLJQJLG6Y',
  );
}
